const HeaderSnapshot = {
  'accept': { name: 'accept', value: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' },
  'accept-encoding': { name: 'accept-encoding', value: 'gzip, deflate, br' },
  'accept-language': { name: 'accept-language', value: 'en-GB,en-US;q=0.9,en;q=0.8' },
  'cache-control': { name: 'cache-control', value: 'max-age=0' },
  'connection': { name: 'connection', value: 'keep-alive' },
  'cookie': { name: 'cookie', value: 'sb-ujctcxghdgnomahgovgp-auth-token-code-verifier=%223e5c8f0f61ccb2b7fc29a9853809472e053c7382265f8e8abd4d4055908421168d96467cae1a970d3a47fe6bc561a38a8934e90e474a079b%22; sb-xasqydhebmzeuuvmsagx-auth-token-code-verifier=%229a77b9980a867997ccf99f195d4fb56c1284ae08e25383ff6bd20e5db0e62510634cc711369c00134572d19dad6a1097ad7a0f5579fb7087%22' },
  'dnt': { name: 'dnt', value: '1' },
  'host': { name: 'host', value: 'localhost:3000' },
  'sec-ch-ua': { name: 'sec-ch-ua', value: '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' },
  'sec-ch-ua-mobile': { name: 'sec-ch-ua-mobile', value: '?0' },
  'sec-ch-ua-platform':{ name: 'sec-ch-ua-platform', value: '"Linux"' },
  'sec-fetch-dest': { name: 'sec-fetch-dest', value: 'document' },
  'sec-fetch-mode': { name: 'sec-fetch-mode', value: 'navigate' },
  'sec-fetch-site': { name: 'sec-fetch-site', value: 'none' },
  'sec-fetch-user': { name: 'sec-fetch-user', value: '?1' },
  'upgrade-insecure-requests': { name: 'upgrade-insecure-requests', value: '1' },
  'user-agent': { name: 'user-agent', value: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' },
  'x-forwarded-for': { name: 'x-forwarded-for', value: '::1' },
  'x-forwarded-host': { name: 'x-forwarded-host', value: 'localhost:3000' },
  'x-forwarded-port': { name: 'x-forwarded-port', value: '3000' },
  'x-forwarded-proto': { name: 'x-forwarded-proto', value: 'http' },
  'x-middleware-next': { name: 'x-middleware-next', value: '1' },
  'x-middleware-override-headers': { name: 'x-middleware-override-headers', value: 'accept,accept-encoding,accept-language,cache-control,connection,cookie,dnt,host,sec-ch-ua,sec-ch-ua-mobile,sec-ch-ua-platform,sec-fetch-dest,sec-fetch-mode,sec-fetch-site,sec-fetch-user,upgrade-insecure-requests,user-agent,x-forwarded-for,x-forwarded-host,x-forwarded-port,x-forwarded-proto' },
  'x-middleware-request-accept': { name: 'x-middleware-request-accept', value: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' },
  'x-middleware-request-accept-encoding': { name: 'x-middleware-request-accept-encoding', value: 'gzip, deflate, br' },
  'x-middleware-request-accept-language': { name: 'x-middleware-request-accept-language', value: 'en-GB,en-US;q=0.9,en;q=0.8' },
  'x-middleware-request-cache-control':{ name: 'x-middleware-request-cache-control', value: 'max-age=0' },
  'x-middleware-request-connection': { name: 'x-middleware-request-connection', value: 'keep-alive' },
  'x-middleware-request-cookie': { name: 'x-middleware-request-cookie', value: 'sb-ujctcxghdgnomahgovgp-auth-token-code-verifier=%223e5c8f0f61ccb2b7fc29a9853809472e053c7382265f8e8abd4d4055908421168d96467cae1a970d3a47fe6bc561a38a8934e90e474a079b%22; sb-xasqydhebmzeuuvmsagx-auth-token-code-verifier=%229a77b9980a867997ccf99f195d4fb56c1284ae08e25383ff6bd20e5db0e62510634cc711369c00134572d19dad6a1097ad7a0f5579fb7087%22' },
  'x-middleware-request-dnt': { name: 'x-middleware-request-dnt', value: '1' },
  'x-middleware-request-host': { name: 'x-middleware-request-host', value: 'localhost:3000' },
  'x-middleware-request-sec-ch-ua': { name: 'x-middleware-request-sec-ch-ua', value: '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' },
  'x-middleware-request-sec-ch-ua-mobile': { name: 'x-middleware-request-sec-ch-ua-mobile', value: '?0' },
  'x-middleware-request-sec-ch-ua-platform': { name: 'x-middleware-request-sec-ch-ua-platform', value: '"Linux"' },
  'x-middleware-request-sec-fetch-dest': { name: 'x-middleware-request-sec-fetch-dest', value: 'document' },
  'x-middleware-request-sec-fetch-mode': { name: 'x-middleware-request-sec-fetch-mode', value: 'navigate' },
  'x-middleware-request-sec-fetch-site': { name: 'x-middleware-request-sec-fetch-site', value: 'none' },
  'x-middleware-request-sec-fetch-user': { name: 'x-middleware-request-sec-fetch-user', value: '?1' },
  'x-middleware-request-upgrade-insecure-requests': { name: 'x-middleware-request-upgrade-insecure-requests', value: '1' },
  'x-middleware-request-user-agent': { name: 'x-middleware-request-user-agent', value: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' },
  'x-middleware-request-x-forwarded-for': { name: 'x-middleware-request-x-forwarded-for', value: '::1' },
  'x-middleware-request-x-forwarded-host': { name: 'x-middleware-request-x-forwarded-host', value: 'localhost:3000' },
  'x-middleware-request-x-forwarded-port': { name: 'x-middleware-request-x-forwarded-port', value: '3000' },
  'x-middleware-request-x-forwarded-proto': { name: 'x-middleware-request-x-forwarded-proto', value: 'http' },
  'x-stoneydsp-request': { name: 'x-stoneydsp-request', value: 'true' }
}
